/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: MKL03Z32xxx4
package_id: MKL03Z32VFK4
mcu_data: ksdk2_0
processor_version: 5.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '13', peripheral: LPUART0, signal: RX, pin_signal: ADC0_SE8/CMP0_IN3/PTB1/IRQ_6/LPUART0_TX/LPUART0_RX/I2C0_SDA}
  - {pin_num: '12', peripheral: SPI0, signal: SCK, pin_signal: ADC0_SE9/PTB0/IRQ_5/LLWU_P4/EXTRG_IN/SPI0_SCK/I2C0_SCL}
  - {pin_num: '19', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, direction: INPUT}
  - {pin_num: '14', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: VREF_OUT/CMP0_IN5/PTB2/IRQ_7/LPUART0_RX/LPUART0_TX, direction: OUTPUT}
  - {pin_num: '17', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: PTB3/IRQ_10/I2C0_SCL/LPUART0_TX, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: PTB4/IRQ_11/I2C0_SDA/LPUART0_RX, direction: OUTPUT}
  - {pin_num: '1', peripheral: GPIOB, signal: 'GPIO, 6', pin_signal: PTB6/IRQ_2/LPTMR0_ALT3/TPM1_CH1/TPM_CLKIN1, direction: OUTPUT}
  - {pin_num: '10', peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: PTB11/TPM0_CH0/SPI0_MISO, direction: OUTPUT}
  - {pin_num: '9', peripheral: SPI0, signal: PCS0_SS, pin_signal: PTB10/TPM0_CH1/SPI0_SS_b}
  - {pin_num: '21', peripheral: GPIOB, signal: 'GPIO, 13', pin_signal: PTB13/CLKOUT32K/TPM1_CH1/RTC_CLKOUT, direction: OUTPUT}
  - {pin_num: '20', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0/CLKOUT, direction: OUTPUT}
  - {pin_num: '11', peripheral: SPI0, signal: MOSI, pin_signal: PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI}
  - {pin_num: '22', peripheral: SWD, signal: SWD_CLK, pin_signal: ADC0_SE15/CMP0_IN2/PTA0/IRQ_0/LLWU_P7/TPM1_CH0/SWD_CLK}
  - {pin_num: '23', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/IRQ_1/LPTMR0_ALT1/TPM_CLKIN0/RESET_b, direction: INPUT}
  - {pin_num: '24', peripheral: SWD, signal: SWD_DIO, pin_signal: PTA2/CMP0_OUT/SWD_DIO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    gpio_pin_config_t gpioa_pin23_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 23)  */
    GPIO_PinInit(GPIOA, 1U, &gpioa_pin23_config);

    gpio_pin_config_t gpioa_pin20_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 20)  */
    GPIO_PinInit(GPIOA, 12U, &gpioa_pin20_config);

    gpio_pin_config_t gpiob_pin14_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 14)  */
    GPIO_PinInit(GPIOB, 2U, &gpiob_pin14_config);

    gpio_pin_config_t gpiob_pin17_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 17)  */
    GPIO_PinInit(GPIOB, 3U, &gpiob_pin17_config);

    gpio_pin_config_t gpiob_pin18_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin 18)  */
    GPIO_PinInit(GPIOB, 4U, &gpiob_pin18_config);

    gpio_pin_config_t gpiob_pin19_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 19)  */
    GPIO_PinInit(GPIOB, 5U, &gpiob_pin19_config);

    gpio_pin_config_t gpiob_pin1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB6 (pin 1)  */
    GPIO_PinInit(GPIOB, 6U, &gpiob_pin1_config);

    gpio_pin_config_t gpiob_pin10_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB11 (pin 10)  */
    GPIO_PinInit(GPIOB, 11U, &gpiob_pin10_config);

    gpio_pin_config_t gpiob_pin21_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB13 (pin 21)  */
    GPIO_PinInit(GPIOB, 13U, &gpiob_pin21_config);

    /* PORTA0 (pin 22) is configured as SWD_CLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt3);

    /* PORTA1 (pin 23) is configured as PTA1 */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAsGpio);

    /* PORTA12 (pin 20) is configured as PTA12 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAsGpio);

    /* PORTA2 (pin 24) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt3);

    /* PORTA7 (pin 11) is configured as SPI0_MOSI */
    PORT_SetPinMux(PORTA, 7U, kPORT_MuxAlt3);

    /* PORTB0 (pin 12) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt3);

    /* PORTB1 (pin 13) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt3);

    /* PORTB10 (pin 9) is configured as SPI0_SS_b */
    PORT_SetPinMux(PORTB, 10U, kPORT_MuxAlt3);

    /* PORTB11 (pin 10) is configured as PTB11 */
    PORT_SetPinMux(PORTB, 11U, kPORT_MuxAsGpio);

    /* PORTB13 (pin 21) is configured as PTB13 */
    PORT_SetPinMux(PORTB, 13U, kPORT_MuxAsGpio);

    /* PORTB2 (pin 14) is configured as PTB2 */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAsGpio);

    /* PORTB3 (pin 17) is configured as PTB3 */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAsGpio);

    /* PORTB4 (pin 18) is configured as PTB4 */
    PORT_SetPinMux(PORTB, 4U, kPORT_MuxAsGpio);

    /* PORTB5 (pin 19) is configured as PTB5 */
    PORT_SetPinMux(PORTB, 5U, kPORT_MuxAsGpio);

    /* PORTB6 (pin 1) is configured as PTB6 */
    PORT_SetPinMux(PORTB, 6U, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0RXSRC_MASK)))

                  /* LPUART0 Receive Data Source Select: LPUART_RX pin. */
                  | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
